'''
Created on 2018. 2. 9.

@author: jihye
'''
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''



def even_fibo(num):
    
    past=1
    current=2
    
    fibo=[1,2]
    
    next=0
    
    while next <= num:
        next=past+current
        fibo.append(next)
        past=current
        current=next
        
    answer=0
    for i in fibo:
        if i % 2 == 0:
            answer+=i
            
    return answer

print(even_fibo(4000000))